system:
  socket-server-ip: 127.0.0.1
  socket-server-port: 9901
  socket-send-file: test.docx
  socket-receive-file: dest.test.docx
  socket-receive-path: /
  send-buffer-size: 1024
  server-buffer-size: 10240

logging:
  level:
    com.tinny: debug
zoo:
  keeper:
    enabled: true
    server: 127.0.0.1:2181
    namespace: zookeeper
    session-timeout-ms: 3000
    connection-timout-ms: 60000
    max-retries: 2
    base-sleep-time-ms: 1000

spring:
  redis:
    cluster:
      nodes: 127.0.0.1:7000, 127.0.0.1:7001, 127.0.0.1:7002, 127.0.0.1:7003, 127.0.0.1:7004, 127.0.0.1:7005
      max-redirects: 3
    #    sentinel:
    #      nodes: 127.0.0.1:6000, 127.0.0.1:6001, 127.0.0.1:6002
    #      master: mymaster
    password: 123
server:
  port: 9800