spring:
  data:
    mongodb:
      uri: mongodb://localhost/nodes
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:config/,classpath:config/licensingservice
server:
  port: 8888